import type { AITool, TaskTemplate } from './types';

// 论文表3.2 原始指标数据 + 扩展的图片/视频生成工具
export const AI_TOOLS: AITool[] = [
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    version: '4.8',
    company: 'Anthropic',
    category: 'llm',
    description: '在知识推理与 Agent 能力上表现突出，适合高难度综合任务与复杂工作流编排。',
    indicators: {
      terminalBench: 0.85,
      sciCode: 0.53,
      liveBench: 0.78,
      gdpvalAA: 0.55,
      tau3Banking: 0.28,
      aaLCR: 0.68,
      omniAccuracy: 0.47,
      omniNonHall: 0.64,
      humanLastExam: 0.46,
      gpqaDiamond: 0.92,
      critpt: 0.21,
      inputPrice: 5.0,
      outputPrice: 25.0,
      tokenForIndex: 120,
      costPerTask: 1.8,
      apiSpeed: 69.8,
    },
    inputPrice: 5.0,
    outputPrice: 25.0,
    tokenForIndex: 120,
    costPerTask: 1.8,
    apiSpeed: 69.8,
    dataSource: 'Artificial Analysis / 官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'gpt-5-5',
    name: 'GPT-5.5',
    version: '5.5',
    company: 'OpenAI',
    category: 'llm',
    description: '在编程、长上下文与专业推理维度全面领先，综合技术优势突出。',
    indicators: {
      terminalBench: 0.84,
      sciCode: 0.56,
      liveBench: 0.8,
      gdpvalAA: 0.5,
      tau3Banking: 0.31,
      aaLCR: 0.74,
      omniAccuracy: 0.57,
      omniNonHall: 0.14,
      humanLastExam: 0.44,
      gpqaDiamond: 0.94,
      critpt: 0.27,
      inputPrice: 5.0,
      outputPrice: 30.0,
      tokenForIndex: 72,
      costPerTask: 0.86,
      apiSpeed: 67.9,
    },
    inputPrice: 5.0,
    outputPrice: 30.0,
    tokenForIndex: 72,
    costPerTask: 0.86,
    apiSpeed: 67.9,
    dataSource: 'Artificial Analysis / 官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'gemini-3-5-flash',
    name: 'Gemini 3.5 Flash',
    version: '3.5 Flash',
    company: 'Google',
    category: 'llm',
    description: '生成速度达到行业顶尖水平，适合对实时性要求高的高频交互场景。',
    indicators: {
      terminalBench: 0.79,
      sciCode: 0.53,
      liveBench: 0.75,
      gdpvalAA: 0.42,
      tau3Banking: 0.25,
      aaLCR: 0.69,
      omniAccuracy: 0.52,
      omniNonHall: 0.39,
      humanLastExam: 0.41,
      gpqaDiamond: 0.92,
      critpt: 0.13,
      inputPrice: 1.5,
      outputPrice: 9.0,
      tokenForIndex: 75,
      costPerTask: 0.59,
      apiSpeed: 183.0,
    },
    inputPrice: 1.5,
    outputPrice: 9.0,
    tokenForIndex: 75,
    costPerTask: 0.59,
    apiSpeed: 183.0,
    dataSource: 'Artificial Analysis / 官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'glm-5-2',
    name: 'GLM-5.2',
    version: '5.2',
    company: 'ZhipuAI',
    category: 'llm',
    description: '国产模型代表，在 Agent 与长上下文维度表现中游，成本控制良好。',
    indicators: {
      terminalBench: 0.78,
      sciCode: 0.5,
      liveBench: 0.76,
      gdpvalAA: 0.51,
      tau3Banking: 0.27,
      aaLCR: 0.71,
      omniAccuracy: 0.25,
      omniNonHall: 0.72,
      humanLastExam: 0.4,
      gpqaDiamond: 0.89,
      critpt: 0.21,
      inputPrice: 1.4,
      outputPrice: 4.4,
      tokenForIndex: 140,
      costPerTask: 0.52,
      apiSpeed: 129.8,
    },
    inputPrice: 1.4,
    outputPrice: 4.4,
    tokenForIndex: 140,
    costPerTask: 0.52,
    apiSpeed: 129.8,
    dataSource: 'Artificial Analysis / 官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    version: 'V4 Pro',
    company: '深度求索',
    category: 'llm',
    description: '成本维度大幅领先，在零预算与成本敏感场景中占据绝对优势，性价比极高。',
    indicators: {
      terminalBench: 0.64,
      sciCode: 0.5,
      liveBench: 0.73,
      gdpvalAA: 0.41,
      tau3Banking: 0.26,
      aaLCR: 0.66,
      omniAccuracy: 0.43,
      omniNonHall: 0.06,
      humanLastExam: 0.36,
      gpqaDiamond: 0.89,
      critpt: 0.13,
      inputPrice: 0.44,
      outputPrice: 0.87,
      tokenForIndex: 180,
      costPerTask: 0.04,
      apiSpeed: 86.9,
    },
    inputPrice: 0.44,
    outputPrice: 0.87,
    tokenForIndex: 180,
    costPerTask: 0.04,
    apiSpeed: 86.9,
    dataSource: 'Artificial Analysis / 官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'kimi-k2-6',
    name: 'Kimi K2.6',
    version: 'K2.6',
    company: 'MoonshotAI',
    category: 'llm',
    description: '国产模型代表，在 Agent 与长上下文等维度表现中游。',
    indicators: {
      terminalBench: 0.57,
      sciCode: 0.53,
      liveBench: 0.72,
      gdpvalAA: 0.35,
      tau3Banking: 0.21,
      aaLCR: 0.7,
      omniAccuracy: 0.33,
      omniNonHall: 0.61,
      humanLastExam: 0.36,
      gpqaDiamond: 0.91,
      critpt: 0.08,
      inputPrice: 0.95,
      outputPrice: 4.0,
      tokenForIndex: 160,
      costPerTask: 0.26,
      apiSpeed: 73.3,
    },
    inputPrice: 0.95,
    outputPrice: 4.0,
    tokenForIndex: 160,
    costPerTask: 0.26,
    apiSpeed: 73.3,
    dataSource: 'Artificial Analysis / 官方定价',
    updatedAt: '2026-08-20',
  },
  // 图片生成工具
  {
    id: 'midjourney-v7',
    name: 'Midjourney',
    version: 'v7',
    company: 'Midjourney',
    category: 'image',
    description: '业界领先的 AI 绘画工具，艺术风格与画面质感出众，适合创意设计与插画创作。',
    indicators: {
      terminalBench: 0,
      sciCode: 0,
      liveBench: 0,
      gdpvalAA: 0,
      tau3Banking: 0,
      aaLCR: 0,
      omniAccuracy: 0,
      omniNonHall: 0,
      humanLastExam: 0,
      gpqaDiamond: 0,
      critpt: 0.92,
      inputPrice: 10,
      outputPrice: 40,
      tokenForIndex: 0,
      costPerTask: 0.1,
      apiSpeed: 8,
    },
    inputPrice: 10,
    outputPrice: 40,
    tokenForIndex: 0,
    costPerTask: 0.1,
    apiSpeed: 8,
    dataSource: '官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'dall-e-4',
    name: 'DALL·E 4',
    version: '4',
    company: 'OpenAI',
    category: 'image',
    description: 'OpenAI 旗舰图像生成模型，文字理解与提示词遵循能力强，集成生态完善。',
    indicators: {
      terminalBench: 0,
      sciCode: 0,
      liveBench: 0,
      gdpvalAA: 0,
      tau3Banking: 0,
      aaLCR: 0,
      omniAccuracy: 0,
      omniNonHall: 0,
      humanLastExam: 0,
      gpqaDiamond: 0,
      critpt: 0.85,
      inputPrice: 4,
      outputPrice: 16,
      tokenForIndex: 0,
      costPerTask: 0.08,
      apiSpeed: 12,
    },
    inputPrice: 4,
    outputPrice: 16,
    tokenForIndex: 0,
    costPerTask: 0.08,
    apiSpeed: 12,
    dataSource: '官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'stable-diffusion-4',
    name: 'Stable Diffusion',
    version: '4',
    company: 'Stability AI',
    category: 'image',
    description: '开源图像生成模型，可本地部署、高度可定制，适合技术型创作者与批量生成。',
    indicators: {
      terminalBench: 0,
      sciCode: 0,
      liveBench: 0,
      gdpvalAA: 0,
      tau3Banking: 0,
      aaLCR: 0,
      omniAccuracy: 0,
      omniNonHall: 0,
      humanLastExam: 0,
      gpqaDiamond: 0,
      critpt: 0.78,
      inputPrice: 0,
      outputPrice: 0,
      tokenForIndex: 0,
      costPerTask: 0,
      apiSpeed: 15,
    },
    inputPrice: 0,
    outputPrice: 0,
    tokenForIndex: 0,
    costPerTask: 0,
    apiSpeed: 15,
    dataSource: '开源 / 官方定价',
    updatedAt: '2026-08-20',
  },
  // 视频生成工具
  {
    id: 'sora-2',
    name: 'Sora',
    version: '2',
    company: 'OpenAI',
    category: 'video',
    description: 'OpenAI 旗舰视频生成模型，画面连贯性与物理理解能力强，适合高质量短视频创作。',
    indicators: {
      terminalBench: 0,
      sciCode: 0,
      liveBench: 0,
      gdpvalAA: 0,
      tau3Banking: 0,
      aaLCR: 0,
      omniAccuracy: 0,
      omniNonHall: 0,
      humanLastExam: 0,
      gpqaDiamond: 0,
      critpt: 0.9,
      inputPrice: 20,
      outputPrice: 80,
      tokenForIndex: 0,
      costPerTask: 0.5,
      apiSpeed: 0.5,
    },
    inputPrice: 20,
    outputPrice: 80,
    tokenForIndex: 0,
    costPerTask: 0.5,
    apiSpeed: 0.5,
    dataSource: '官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'kling-2',
    name: '可灵 Kling',
    version: '2.0',
    company: '快手',
    category: 'video',
    description: '国产领先视频生成模型，长视频生成与运镜控制出色，性价比高。',
    indicators: {
      terminalBench: 0,
      sciCode: 0,
      liveBench: 0,
      gdpvalAA: 0,
      tau3Banking: 0,
      aaLCR: 0,
      omniAccuracy: 0,
      omniNonHall: 0,
      humanLastExam: 0,
      gpqaDiamond: 0,
      critpt: 0.82,
      inputPrice: 5,
      outputPrice: 20,
      tokenForIndex: 0,
      costPerTask: 0.15,
      apiSpeed: 1,
    },
    inputPrice: 5,
    outputPrice: 20,
    tokenForIndex: 0,
    costPerTask: 0.15,
    apiSpeed: 1,
    dataSource: '官方定价',
    updatedAt: '2026-08-20',
  },
  {
    id: 'runway-gen4',
    name: 'Runway',
    version: 'Gen-4',
    company: 'Runway',
    category: 'video',
    description: '专业视频创作平台，支持图生视频、风格迁移与精细控制，适合影视与广告制作。',
    indicators: {
      terminalBench: 0,
      sciCode: 0,
      liveBench: 0,
      gdpvalAA: 0,
      tau3Banking: 0,
      aaLCR: 0,
      omniAccuracy: 0,
      omniNonHall: 0,
      humanLastExam: 0,
      gpqaDiamond: 0,
      critpt: 0.8,
      inputPrice: 15,
      outputPrice: 60,
      tokenForIndex: 0,
      costPerTask: 0.3,
      apiSpeed: 0.8,
    },
    inputPrice: 15,
    outputPrice: 60,
    tokenForIndex: 0,
    costPerTask: 0.3,
    apiSpeed: 0.8,
    dataSource: '官方定价',
    updatedAt: '2026-08-20',
  },
];

// 任务模板（含 7 维需求向量 r_jk 与平均 token 量）
export const TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: 'paper-writing',
    name: '论文写作',
    description: '撰写学术论文、润色与结构优化',
    icon: 'FileText',
    demands: { coding: 0.2, agent: 0.2, longContext: 0.6, knowledge: 0.85, reasoning: 0.8, cost: 0.4, speed: 0.3 },
    avgInputTokens: 8000,
    avgOutputTokens: 3000,
  },
  {
    id: 'literature-analysis',
    name: '文献分析',
    description: '文献综述、要点提取与对比分析',
    icon: 'BookOpen',
    demands: { coding: 0.2, agent: 0.3, longContext: 0.95, knowledge: 0.8, reasoning: 0.75, cost: 0.5, speed: 0.4 },
    avgInputTokens: 50000,
    avgOutputTokens: 4000,
  },
  {
    id: 'data-analysis',
    name: '数据分析',
    description: '数据清洗、统计分析与可视化',
    icon: 'BarChart3',
    demands: { coding: 0.7, agent: 0.5, longContext: 0.4, knowledge: 0.6, reasoning: 0.8, cost: 0.4, speed: 0.5 },
    avgInputTokens: 6000,
    avgOutputTokens: 2000,
  },
  {
    id: 'python-coding',
    name: 'Python 编程',
    description: '代码生成、调试与工程实现',
    icon: 'Code2',
    demands: { coding: 0.95, agent: 0.35, longContext: 0.4, knowledge: 0.65, reasoning: 0.9, cost: 0.2, speed: 0.5 },
    avgInputTokens: 4000,
    avgOutputTokens: 2000,
  },
  {
    id: 'ppt-making',
    name: 'PPT 制作',
    description: '演示文稿大纲、内容与排版辅助',
    icon: 'Presentation',
    demands: { coding: 0.3, agent: 0.4, longContext: 0.5, knowledge: 0.7, reasoning: 0.6, cost: 0.4, speed: 0.6 },
    avgInputTokens: 5000,
    avgOutputTokens: 3000,
  },
  {
    id: 'image-generation',
    name: '图片生成',
    description: 'AI 绘画、海报与插画创作',
    icon: 'Image',
    demands: { coding: 0, agent: 0, longContext: 0, knowledge: 0, reasoning: 0, cost: 0.5, speed: 0.8 },
    avgInputTokens: 0,
    avgOutputTokens: 0,
  },
  {
    id: 'video-generation',
    name: '视频生成',
    description: 'AI 视频创作、图生视频与运镜',
    icon: 'Video',
    demands: { coding: 0, agent: 0, longContext: 0, knowledge: 0, reasoning: 0, cost: 0.6, speed: 0.7 },
    avgInputTokens: 0,
    avgOutputTokens: 0,
  },
  {
    id: 'information-retrieval',
    name: '信息检索',
    description: '实时搜索、事实核查与资料整理',
    icon: 'Search',
    demands: { coding: 0.2, agent: 0.5, longContext: 0.5, knowledge: 0.9, reasoning: 0.6, cost: 0.5, speed: 0.8 },
    avgInputTokens: 3000,
    avgOutputTokens: 1500,
  },
  {
    id: 'agent-automation',
    name: 'Agent 自动化',
    description: '多步任务编排、工具调用与自动化流程',
    icon: 'Workflow',
    demands: { coding: 0.5, agent: 0.9, longContext: 0.55, knowledge: 0.8, reasoning: 0.6, cost: 0.45, speed: 0.7 },
    avgInputTokens: 10000,
    avgOutputTokens: 4000,
  },
  {
    id: 'deep-reasoning-code',
    name: '深度推理与代码工程',
    description: '复杂逻辑推理与大型代码工程',
    icon: 'BrainCircuit',
    demands: { coding: 0.95, agent: 0.35, longContext: 0.4, knowledge: 0.65, reasoning: 0.9, cost: 0.2, speed: 0.5 },
    avgInputTokens: 6000,
    avgOutputTokens: 2500,
  },
  {
    id: 'long-text-doc',
    name: '长文本检索与文档解析',
    description: '超长文档解析、检索与摘要',
    icon: 'FileSearch',
    demands: { coding: 0.25, agent: 0.5, longContext: 0.95, knowledge: 0.5, reasoning: 0.45, cost: 0.8, speed: 0.6 },
    avgInputTokens: 100000,
    avgOutputTokens: 3000,
  },
  {
    id: 'daily-qa',
    name: '日常问答',
    description: '日常对话、搜索替代与偶发写作',
    icon: 'MessageCircle',
    demands: { coding: 0.3, agent: 0.3, longContext: 0.3, knowledge: 0.6, reasoning: 0.4, cost: 0.9, speed: 0.7 },
    avgInputTokens: 1500,
    avgOutputTokens: 800,
  },
];